czech.txt
Removed obsolete rules and added updated from [cz/sk uBlock rules](https://github.com/tomasko126/easylistczechandslovak/blob/master/filters_ublock.txt).
=> Update czech filters

english.txt
Update script on thoughtcatalog com, ads showing because of it :)
=> Update rule for https://thoughtcatalog com/

english.txt
Just the update the string being used.
=> M: Update reuters.com

arabic.txt
Not sure what the #! comments represent, but here is a fix for the site.
Can modify pull req if a ! comment is needed.
=> Stop popups being generated for https://github.com/abp-filters/abp-filters-anti-cv/issues/194

english.txt
https://github.com/abp-filters/abp-filters-anti-cv/commit/8117aa309ee849a2a986359209435e73bb447245#r34584804
=> M: added separator

spanish.txt
Report here;
`https://forums.lanik.us/viewtopic.php?f=62&t=43374`
=> Fix popups on https://topflix.tv/series/assistir-online-rick-and-morty/

english.txt
Not sure if this was the right section, but adjust to the right area if need be.
=> Fix popups on https://3movierulz.tv/aladdin-2019-hdrip-full-movie-watch-online-free/

english.txt
new popunder
adapted from ublock
https://i.imgur.com/1QDApck.jpg
=> M: NSFW xhamster.com

english.txt
Blocking this script should prevent the ads from showing.
=> Block instart ads on metacritic.com

english.txt
Fix `dronedj.com` another 9to5 site. using `Apomaya`
=> Add fix for related 9to5 site dronedj.com

arabic.txt
as seen on `https://animetak.net/episodes/%D8%A7%D9%86%D9%85%D9%8A-mairimashita-iruma-kun-%D8%A7%D9%84%D8%AD%D9%84%D9%82%D8%A9-14-%D9%85%D8%AA%D8%B1%D8%AC%D9%85%D8%A9-%D8%A7%D9%88%D9%86-%D9%84%D8%A7%D9%8A%D9%86.html`
=> Fix ads on animetak.net

english.txt
From: `http://movies123.xyz/watch/drbRzALd-uncut-gems/other.html`
And 2 mirrors from `prostream.to` `vidlox.me` Using the same adservers.
Test urls: `http://prostream.to/peyhbqyyzek3.html`
`https://vidlox.me/j7s63eokkie8`
=> Fix ads on various movies123.xyz sites

english.txt
Same ads from on 9to5google, 9to5mac etc.
=> Fix ads on kansas.com

english.txt
Update `mystream.to` mirrot domains.
e.g `https://mstream.xyz/9kny7ewukvrt` (popup)
=> A: MISC #121

czech.txt
Hi,
the maintainers of the czech easylist insist I use uBlock - but I'd like to block the ads for the general public too.
=> Blocking circumvention ads on horoskopy.cz

polish.txt
* `https://www.sportowefakty.wp.pl/`
</details>
* ABP filters
* similar to #408 
* `#$#abort-on-property-read prebidConfig.config.bidTargets` might break links on other `wp.pl` subsites, but seems to work fine with `sportowefakty.`
=> sportowefakty.wp.pl

polish.txt
located some CV issues on some polish websites, and the following snippets work on them.
=> added polish snippets

polish.txt
* `https://www.gwiazdy.wp.pl/`
* `https://www.o2.pl/`
* `https://www.autokult.pl/`
</details>
* ABP filters
=> gwiazdy.wp.pl,o2.pl,autokult.pl

polish.txt
* `https://www.kardiolo.pl/`
* `https://www.forum.echirurgia.pl/`
</details>
* ABP filters
=> kardiolo.pl,forum.echirurgia.pl

polish.txt
* `https://www.film.wp.pl/`
* `https://www.teleshow.wp.pl/`
</details>
* ABP filters
=> film.wp.pl,teleshow.wp.pl

polish.txt
* `https://www.pogoda.wp.pl/`
* `https://www.wawalove.wp.pl/`
</details>
* ABP filters
=> pogoda.wp.pl,wawalove.wp.pl

polish.txt
* `https://opinie.wp.pl/`
* `https://facet.wp.pl/`
* `https://facet.wp.pl/garnitury-i-koszule-na-lato-lekkie-i-przewiewne-modele-6530236037990529a`
</details>
* ABP filters
=> opinie.wp.pl,facet.wp.pl

polish.txt
* `https://autocentrum.pl/`
* `https://kuchnia.wp.pl/`
</details>
* ABP filters
=> autocentrum.pl,kuchnia.wp.pl

spanish.txt
For blocking inline script that redirects on the first click on pctnew.org
=> pctnew.org

polish.txt
* `https://horoskop.wp.pl/artykuly/wibracje-numerologiczne-na-sierpien-2020-1`
* `https://ksiazka.wp.pl/`
</details>
* ABP filters
- Browser and version: Opera 70.0
=> horoskop.wp.pl,ksiazka.wp.pl

polish.txt
https://github.com/abp-filters/abp-filters-anti-cv/pull/443#issuecomment-677435190
=> ksiazki.wp.pl

polish.txt
* `https://tech.wp.pl/`
* `https://turystyka.wp.pl/`
</details>
* ABP filters
- Browser and version: Opera 70.0
=> tech.wp.pl,turystyka.wp.pl

polish.txt
* `https://money.pl/`
* `https://moneyv.wp.pl/` (host some articles from `money.pl`)
* `https://twojeip.wp.pl/`
</details>
* ABP filters
- Browser and version: Opera 70.0
=> money.pl,moneyv.wp.pl,twojeip.wp.pl

spanish.txt
=> animeflv.cc

polish.txt
* `https://parenting.pl/baby-blues-nie-boj-sie-prosic-o-wsparcie`
* `https://moto.wp.pl/` 
* `https://finanse.wp.pl/`
</details>
* ABP filters
- Browser and version: Opera 70.0
=> parenting.pl,moto.wp.pl,finanse.wp.pl

english.txt
We could block these ads easier with a snippet.
No need to block elements. If we abort the JSON.stringify used on the site it'll fix this ad elements.
=> Improve ign.com, ignboards.com filter

polish.txt
* `https://naekranie.pl/`
<details><summary>more info</summary>
* ABP filters
- Browser and version: Opera 71.0
- Adblock Plus version: 3.10
</details>
--
=> naekranie.pl

polish.txt
https://github.com/abp-filters/abp-filters-anti-cv/pull/528#issuecomment-756174519
=> WP group - filter fix

polish.txt
* `https://www.o2.pl`
* `https://www.wp.pl` 
* ABP filters
- Browser and version: Opera 72.0
- Adblock Plus version: 3.10
</details>
To block most of the ads on the **main** sites
=> WP group 2

czech.txt
=> Update czech.txt - sreality.cz

vietnamese.txt
Process lb.topphimhd.info (iframe in motphimmoi.net)
=> Add vietnamese.txt

indian.txt
Prevents redirects to other domains when clicking on a video.
=> A: xxx-indian-porn.com

english.txt, spanish.txt
Block redirect popup on Spanish website [animefenix.com](https://www.animefenix.com/) triggered after clicking on 'Inicio' or any chapter.
`animefenix.com#$#abort-current-inline-script document.createElement _yzvesi`
=> A: #FDA-2333

english.txt
Adding domain: gomovie.ms to rule: `#$#abort-on-property-read atob` in order to block redirect popups.
=> A: FDA-2408

czech.txt
=> seznamzpravy.cz

vietnamese.txt
=> A: biphimtv.net popup/popupunder

arabic.txt
**Website**
* `https://yalla-shoot.today/`
**Problem**
* popups
**List all of your filter lists**
* ABP filters
* EasyList + Liste FR + Liste AR
* EasyPrivacy
=> A: MISC #751

vietnamese.txt
Refer: uBlockOrigin/uAssets#10936
=> A: ephimmoi.net popup

arabic.txt
**problem**:
* popups 
**site**: 
- movizland.cyou
=> A: MISC #853

vietnamese.txt
Fix video can't play
**Step to reproduce:**
1. Go to https://hhhkungfu.tv/xem-phim-dau-pha-thuong-khung-ova-uoc-hen-3-nam/ep-13-sv1.html
2. Select **Link 3**
3. Click to video to play
Also can access url in iframe directly: https://watchsb.com/e/s95m4jht0jlr.html to reproduce
**Actual:**
Video can't play
**Expect:**
Video can play
**Enabled Filters:**
- EasyList
- ABPVN List
- ABP Filters
=> A: hhhkungfu.tv

english.txt
**problem**:
* popup
**site**: 
- `1337x.buzz`
=> A: MISC #882

french.txt
**problem**:
* popup
**site**: 
- `torrent911.com`
=> A: MISC #883

vietnamese.txt
1. Hide modal place holder
2. Remove redirect ads
=> A: xoilac2.net

vietnamese.txt
=> M: MISC #896

czech.txt
seznamzpravy.cz - several blocking methods at once
=> Update czech.txt - seznamzpravy.cz

vietnamese.txt
ezphimmoi.net now redirect to bphimmoi.net
=> D: ezphimmoi.net

vietnamese.txt
Block ads modal on plus.gtv.vn
=> A: plus.gtv.vn

indonesian.txt
**problem**:
* background link/popup
**site**:
```
hotabis.com
```
=> A: MISC #944

vietnamese.txt
These website change their popup script so I update snippet rule to block it
=> M: baliphim.com,lucaphim.com abpvn/abpvn#393

vietnamese.txt
Step to reproduce:
1. Go to https://phimmoii123.com/phim/9849-ha-tien-sinh-luu-luyen-khong-quen
2. Click on orange button popunder will be show
=> A: phimmoii123.com

vietnamese.txt
=> A: bongdahomnay.tech

vietnamese.txt
Step to reproduce:
1. Visit https://phimhays.com/
2. Click to any movie poster. An google popup will be show
=> A: phimhays.com

vietnamese.txt
Domain mitom.90phutttttttt.xyz now is mitom.90phuttttttttt.xyz
=> M: 90phutttttttt.xyz -> 90phuttttttttt.xyz

vietnamese.txt
Step to reproduce:
1. Access website vebotv.vip
2. An blank modal will be show. This rule will block this modal
<details>
<summary>Screenshot:</summary>
</details>
=> A: vebotv.vip

vietnamese.txt
This rule to block fake notification in the right side of website
<details>
<summary>Screenshot</summary>
</details>
=> A: tvhay.top

vietnamese.txt
Click to anywhere in website will open popup
=> A: truyentranhtuan.com

english.txt
Block adservers requests at https://animepahe.com/
Screenshot:
=> MISC #1000

english.txt
Block initiators at https://yomovies.ws/
Screenshot:
=> MISC #1003

vietnamese.txt
=> M: vebotv.vip -> vebotv.xyz

english.txt
Block adservers initiators at https://prmovies.re/
Screenshot:
=> MISC #1005

english.txt
Block popunders at https://tpbay.link/
Screenshot:
=> MISC #1007

spanish.txt
Block adserver initiators at https://pelismart.com/
=> MISC #1008

vietnamese.txt
This domain and rule now out date so I remove it
=> D: xoilac2.net

vietnamese.txt
=> M: phimhdvns.net -> ophimhd.net

english.txt
Block initiators at https://manhuascan.io/
Screenshot:
=> MISC #1014

english.txt
Block initiators at https://atomohd.org/
=> MISC #1018

spanish.txt
Block popups at https://monoschinos2.com/
=> MISC #1019

vietnamese.txt
=> M: vzphimmoi.net -> vnphimmoi.net

spanish.txt
Block adservers to initiate at: 
http://www.bajarpelisgratis.com/
https://www.torrentdownloads.pro/
https://gnula.se/
=> MISC #1024

english.txt
Block popup messages + redirects at https://moviesda1.com/
=> MISC #1031

italian.txt
Block adservers initiators at https://www.animeunity.tv/
=> MISC #1032

spanish.txt
Block initiators at https://tmomanga.com/
Screenshot:
=> MISC #1035

english.txt, spanish.txt
Block adservers initiators at 
[NSFW] https://hentai20.com/
Screenshot:
=> MISC #1038

arabic.txt
Popmagic at [NSFW] https://www.arabxd.com/
=> MISC #1039

indonesian.txt
Block popups at https://komikcast.me/
Screenshot:
=> MISC #1041

english.txt
Block adservers to initiate at https://wiflix.bet/
=> MISC #1042

vietnamese.txt
=> A: vebo.live

spanish.txt
Block initiators/popup messages at https://futbollatam.com/
=> MISC #1044

german.txt
Block popup messages / popups at https://www.yabeat.org/
Screenshot:
=> MISC #1050

english.txt
Block initiators at https://manga21plus.com/
Screenshot:
=> MISC #1051

english.txt
Block initiators at
https://www3.zoechip.com/
https://www6.f2movies.to/
https://gogoanime.run/
https://tinyzonetv.to/
https://watchseries.ma/
=> MISC #1052

french.txt
Bloock initiators at:
http://www.papystreamings.com/
=> MISC #1055

spanish.txt
Block initiators at https://pelispoptv.com/
=> MISC #1056

vietnamese.txt
=> M: MISC #1060

english.txt
Block initiators at 
https://filmlinks4u.cam/
https://123movies-official.net/
=> MISC #1063

vietnamese.txt
Block popup on lphim.net
Step to reprocedure:
1. Visit lphim.net
2. Click to anywhere popup will be show
=> A: MISC #1065

english.txt
Block initiators at: 
https://soap2day.cloud/
=> MISC #1066

spanish.txt
Popmagic at https://hentaila.tv/
=> MISC #1068

spanish.txt
Block initiators at https://gnula.nu/
=> MISC #1070

english.txt
https://watchseries.im/ (https://watchseries.ma/watch-tv/watch-ms-marvel-free-78142.8528728) 
https://manhuascan.io/read-19-days-chapter-393.html
=> M: Fix (videos/images not loading)

indonesian.txt
**problem**:
* popunder
**site**: 
- `solusi.cyou`
- `beritabaru.news`
=> A: MISC #1071

french.txt
Block iniatiators at https://vww.voirseries.rip/
=> MISC #1077

french.txt
Block initiators at https://www.blablastream.rip/
=> MISC #1079

english.txt
Block initators at: 
https://hdtoday.tv/
=> MISC #1076

arabic.txt
=> A: MISC #1080

english.txt, french.txt
Block initiators at https://yomovies.cam/
=> MISC #1082

vietnamese.txt
Remove domain baliphim.com,lucaphim.com because it is not accessible from now
=> D: MISC (#1083)

vietnamese.txt
Block popup script generator on subnhanh.net
=> A: MISC (#1084)

english.txt, spanish.txt
Block initiators at https://readmanganato.com/
=> MISC #1085

vietnamese.txt
Block preroll video in luotphim1.com
=> A: MISC (#1089)

spanish.txt
Popup/unders at calidadcine.net#$#abort-on-property-read https://calidadcine.net/
=> MISC #1095

english.txt
Block popups at https://www.limetorrents.lol/
=> MISC #1097

vietnamese.txt
=> A: MISC (#1105)

english.txt
Block initiators at [NSFW] https://manhwaclub.net/
Screenshot:
=> MISC #1107

indian.txt
Block initiators at [NSFW] https://moredesi.com/
=> MISC #1108

spanish.txt
Block initiators at [NSFW] http://peladas69.com/
=> MISC #1109

english.txt
Block initiators at [NSFW] https://tube.perverzija.com/
=> MISC #1110

spanish.txt
Block initiators at https://pelisnow.to/
=> MISC #1118

arabic.txt
**sites**
```
cima-club.lol
cima4u.ink
cimalina.me
cimalina.net
iegybest.co
shahed4u.cafe
shahed4u.mba
tuktukcinema.net
```
=> A: MISC #1120

spanish.txt
Block popups from voe proxy at https://doramasqueen.com/ and potential other pages.
Example:
https://doramasqueen.com/capitulo/bad-romeo-2022-capitulo-1-temporada-1
=> MISC #1122

vietnamese.txt
Update redirect domain from vebotv.xyz to vebotv.site
=> M: MISC (#1123)

vietnamese.txt
Update redirect domain
phimmoiii123.com -> phimmoiiii123.com
=> M: MISC #1127

vietnamese.txt
Update domain redirection
vebo.live -> vebo1.com
=> M: MISC #1129

vietnamese.txt
Block popup in iphimchillzz.net
=> A: MISC #1133

vietnamese.txt
Update domain redirection vebo1.com -> vebo1.tv
=> M: MISC #1138

english.txt
Block initiators at https://igg-games.com/
Screenshot:
=> MISC #1139

english.txt
Block initiator at yts.mx
Screenshot:
=> MISC #1140

vietnamese.txt
Update redirection and add domain of luotphim series
=> M: MISC #1146

vietnamese.txt
Block popup on **[NSFW]** lxhentai.com
=> M: MISC #1147

vietnamese.txt
Update domain redirection luotphim.top -> luotphim.to
=> M: MISC #1153

vietnamese.txt
Block preroll ads in vuighe.net, mehoathinh.com
=> M: MISC #1157

english.txt
https://www.toongod.com/
`toongod.com#$#abort-on-property-read window.open`
https://readcomiconline.li/
`toongod.com#$#abort-on-property-read window.open`
Actually blocking disqus comments (JSON.parse)
https://www.japscan.me/
`japscan.me#$#abort-on-property-read window.open`
=> MISC #1158

vietnamese.txt
Block popup on quangcaoyenbai.com
=> A: MISC #1162

vietnamese.txt
Block popup on fullcrackpc.com
=> A: MISC #1164

vietnamese.txt
Remove to fix video next button + This ads video can be blocked by normal network rule
=> D: MISC #1165 fix abpvn/abpvn#459

vietnamese.txt
=> A: MISC #1166

vietnamese.txt
Remove parked domain [NSFW] `lxhentai.com`
=> D: MISC #1168

english.txt
Popunders at https://liveru.sx/
=> MISC #1172

vietnamese.txt
Update domain change from 90phut2.live to 90phut6.live
=> M: MISC #1174

vietnamese.txt
Update domain redirection xemphimgif.net -> phimgif.tv
=> M: MISC #1176

english.txt
Block initiators at https://hurawatch.cc/
=> MISC #1177

english.txt
Popunders at [NSFW] https://udvl.com/
=> MISC #1189

vietnamese.txt
=> [NSFW] A: MISC #1192

english.txt
Block Popunders at [NSFW] https://toon69.com/
=> MISC #1193

vietnamese.txt
Block overlay ads in xoilac5.live
=> A: MISC #1194

vietnamese.txt
Block popup on viet69.gg and sex6688.link
=> [NSFW] M: MISC #1196 abpvn/abpvn#467

vietnamese.txt
Block video ads on phimmoik.com
=> A: MISC #1120 abpvn/abpvn#468

vietnamese.txt
Remove dead domain in Vietnam phimhay3s.com
=> D: MISC #1210

english.txt
https://github.com/easylist/easylist/issues/14047
=> A: MISC #1211

vietnamese.txt
Block pop under in sexvietnam.site
abpvn/abpvn#476
=> [NSFW] A: MISC #1212 abpvn/abpvn#476

vietnamese.txt
Block popup on ophimmoi.net
Ref: abpvn/abpvn#479
=> A: MISC #1213 abpvn/abpvn#479

vietnamese.txt
Block preroll video on webphim1.com
Ref: abpvn/abpvn#477
=> A: MISC #1214 abpvn/abpvn#477

vietnamese.txt
Block popunder ads on `phimhoathinh3d.com`
Reference: abpvn/abpvn#481
=> A: MISC #1219 abpvn/abpvn#481

vietnamese.txt
=> D: MISC #1221

english.txt
**problem**:
- popups
**site**: 
- `https://vidplay.ch/e/wk23guc5frch` / #1222
=> A: MISC #1229

vietnamese.txt
Block popup on linkneverdie.net
=> A: MISC #1235

vietnamese.txt
Update domain redirection viet69.gg -> viet69.tv
=> [NSFW] M: MISC #1240

vietnamese.txt
Update popup script and bait in linkneverdie.net
=> M: MISC #1244

vietnamese.txt
* Remove out date rule
* Update domain redirection
=> M: MISC #1251

english.txt
Popunders at [NSFW] https://www.onscreens.me/
=> MISC #1253

vietnamese.txt
Remove outdate rule + update function change
=> M: MISC #1257

vietnamese.txt
Block popup ads in truyen2u.net
=> M: MISC #1261

vietnamese.txt
Both xoilac19.tv and xoilac19.net now redirected to xoilac21.tv
=> M: MISC #1262

vietnamese.txt
Block new popup in linkneverdie.net
=> M: MISC #1263

vietnamese.txt
Fix login issue on linkneverdie.net by use override-property-read instead of abort-on-property-read
=> M: MISC #1265

vietnamese.txt
Block ads loaded use tag manager and randomize domain in cafef.vn,gamek.vn,genk.vn,kenh14.vn
=> A: MISC #1273

vietnamese.txt
Change popup block method in linkneverdie.net to fix link/button click
=> M: MISC #1274

vietnamese.txt
Block popup/popunder in vlxxs.net
Ref abpvn/abpvn#499
=> [NSFW] A: MISC #1277

vietnamese.txt
Block popup on viet69.lol
Reference: abpvn/abpvn#507
=> [NSFW] A: MISC #1279

vietnamese.txt
=> A: MISC #1281

vietnamese.txt
Block notify style ads in truyen86.com
=> A: MISC #1284

vietnamese.txt
Update domain change + new replica domain subnhanh.cc
=> M: MISC #1286

vietnamese.txt
Remove useless scriplet in linkneverdie.net
=> M: MISC #1287

english.txt
Please add the following snippet to stop the popunders/popups on the page. Thank you
=> A: (nsfw)`socialmediagirls.com`

english.txt
Hi, please add the domain to the existing filter, it keeps redirecting me in another tab and popping with ads in the previous tab.  Thanks a lot
=> A: `socialmediagirls.com`

vietnamese.txt
Block popup/popunder in ungtycomicsvip.com
=> A: MISC #1290

vietnamese.txt
Update domain redirect from `viet69.lol -> viet69.page`
=> [NSFW] M: MISC #1296

vietnamese.txt
Block popup/popunder in `vlxx.info`
=> [NSFW] A: MISC #1297

vietnamese.txt
Block popup/popunder in `sexdiaryz.fun`
Remove out date rule in `phimhoathinh3d.com`
Reference: abpvn/abpvn#519
=> [NSFW] A: MISC #1300

portuguese.txt
Popup banner at https://torrentdosfilmes.eu/
=> MISC #1308

vietnamese.txt
Update snippet in `linkneverdie.net`
=> M: MISC #1311

vietnamese.txt
Update domain redirection from `viet69.page` to `viet69.love`
=> [NSFW] M: MISC (#1314)

vietnamese.txt
=> D: MISC (#1316)

vietnamese.txt
Block ads script loader via createObjectURL in `baomoi.com` and `zingnews.vn`
=> A: MISC (#1331)

vietnamese.txt
Remove dead domain `sex68.link`
=> [NSFW] D: MISC (#1332)

vietnamese.txt
Block preroll video ads in `bongda365a.net`
=> A: MISC (#1333)

vietnamese.txt
Fix site slow load in `viet69.love`
Reference: abpvn/abpvn#529
=> [NSFW] M: MISC (#1342)

vietnamese.txt
Block ads script loader via ObjectUrl in baomoi.com, zingnews.vn
=> M: MISC (#1346)

vietnamese.txt
Block popup ads on `truyengihotne.com`
Ref: uBlockOrigin/uAssets#17779
=> A: MISC (#1349)

vietnamese.txt
Remove useless rule and false positive in zingnews.vn and baomoi.com
These site change ads load method
Ref: abpvn/abpvn#531
=> D: MISC (#1351)

vietnamese.txt
Update ADS script loader in the site `cafef.vn,gamek.vn,genk.vn,kenh14.vn`
=> M: MISC (#1354)

vietnamese.txt
Fix error in `linkneverdie.net`
=> M: MISC (#1359)

vietnamese.txt
Block mobile ads loader in `zingnews.vn`
=> A: MISC (#1361)

vietnamese.txt
Block popup on `khoaiphim.com`
=> A: MISC (#1364)

vietnamese.txt
Block new ads loader type in `baomoi.com`
=> M: MISC (#1365)

english.txt
greeting popup =>
- ad blocker detected => clicking x -> popup
- no ad blocker detection => window apparently opens and closes
=> A: MISC #632

vietnamese.txt
Block popup in `phimdinhcao.net,phimlongtieng.net,phimdinhcao.com`
=> A: MISC (#1371)

vietnamese.txt
Fix video player loading infinity
Ref: abpvn/abpvn#541
Url: https://animehay.io/xem-phim/highschool-of-the-dead-tap-11-5251.html
=> M: MISC (#1380)

vietnamese.txt
Block popup on protruyen.com,animevietsub.moe and optimize old rule
=> M: MISC (#1384)

vietnamese.txt
=> A: MISC(#1387)

vietnamese.txt
Update domain redirection
* `phimgiff.net` redirect to `phimgihd.net` exist in bottom
* `ophimmoi.net` redirect to `phimmoik.net` and has no popupurl
* `vaoroi13.online` is not accessible
* `hephimmoi.net` is redirect to `phimmoipro.net` and rule is outdate
* `nguontvhd.com` is redirect to `nguontv1.com` and rule is outdate
* `xoilac4.com` is redirect to `xoilac78.tv`
=> M: MISC(#1388)

vietnamese.txt
Block popup on `phimmoi4s.com`
=> M: MISC(#1391)

vietnamese.txt
Block popup in `khoaiphim.com`
=> A: MISC(#1392)

vietnamese.txt
Block popup/popunder in `dualeotruyenz.com`
=> A: MISC(#1394)

english.txt
- `https://sblona.com/e/n46l0uvyqvc4.html` (https://github.com/abp-filters/abp-filters-anti-cv/issues/1222)
=> A: MISC #1395

vietnamese.txt
Block preroll video ads in `luotphim2.net`
=> A: MISC(#1397)

vietnamese.txt
Update domain redirection `phimgihd.net` -> `phimgivn.net`
=> M: MISC(#1398)

vietnamese.txt
Add block popup on `dualeotruyenz.com`
=> A: MISC(#1400)

vietnamese.txt
Block ads on `soha.vn` and fix incorrect snipplet
=> A: MISC(#1401)

vietnamese.txt
Block `admicro.vn` ads loader in `tuoitre.vn`
It stop blocked count on ABP icon inrease on scroll
=> A: MISC(#1402)

vietnamese.txt
Block popup/popunder in `lxmanga.net`
=> [NSFW] A: MISC(#1403)

vietnamese.txt
Block popup/popunder on `ophim.vip`
=> A: MISC(#1404)

vietnamese.txt
Block preroll video ads on `xoivo7.info`
=> A: MISC (#1406)

vietnamese.txt
Block ads script loader in `kenh14.vn`
=> A: MISC(#1408)

vietnamese.txt
Remove kenh14.vn in this rule because ABP only accept single snippet rule on a site
=> D: MISC(#1409)

vietnamese.txt
Block ads download countdown in `vndoc.com`
Ref: https://vndoc.com/download/tuyen-tap-37-de-thi-hoc-ki-1-mon-toan-lop-2-103293
=> A: MISC(#1410)

vietnamese.txt
Block preroll ads in `vaoroi13.online`
=> A: MISC(#1412)

vietnamese.txt
Block popup in `https://truyen35.vn/vu-luyen-dien-phong/chuong-5`
=> A: MISC(#1413)

vietnamese.txt
Update domain redirection from 
* `phimgivn.net` to `phimgi1.net`
* `xoilac78.tv` to `xoilac79.tv`
* `dualeotruyenz.com` to `dualeotruyenk.com`
* `zo3x.ml` to `zo3x.lol`
=> M: MISC(#1418)

vietnamese.txt
=> A: MISC(#1419)

vietnamese.txt
Remove incorrect rule on `linkneverdie.net`
=> M: MISC(#1420)

vietnamese.txt
Update domain redirection `phimgi1.net` to `phimgigi.net`
=> M: MISC(#1422)
