abp-filters/abp-filters-anti-cv

german.txt

added a german third-party media advertisor which circumvents ABP

A: vidapi.expepp.de (third-party)

---

english.txt

**@@$media,domain=gamespot.com**
This is needed, because the site is using fake media elements. (Specifically). I can make it specific, but these domain checks could change.
`@@||g00.gamespot.com^$media,domain=gamespot.com`
`@@||revcontent.com^$media,domain=gamespot.com`
`@@||2mdn.net^$media,domain=gamespot.com`
`@@||doubleverify.com^$media,domain=gamespot.com`
`@@||betrad.com^$media,domain=gamespot.com`
`@@||openx.net^$media,domain=gamespot.com`
**@@||gamespot.com^$generichide**
The site will essentially render broken without this, because instart will start checking for ad divs. So image/videos will appear correctly.
**@@||securepubads.g.doubleclick.net/..**
These whitelists will allow the articles to be shown, instead of a blank page.

Fix Instart ads on gamespot.com

---

english.txt

Similar fix to gamespot, using the same fake $media checks.
Should make msn.com a bit more readable. may need to clean up those msn.com filters you have ;)

Fix msn.com (instart ads)

---

english.txt

Just an update on filters being used on pch.com (US VPN needed)
`https://www.pch.com/games/matching/played-mahjongg-flower-power/gameplay`
Would recommend muting site. the tune, its.. bad.

Fix pch.com instart ads

---

english.txt

The following domains are dead, no longer active.
`tetrisfriends.com`
`movpod.in`
`asheepnomore.net`
`gorillavid.in`
`anime-vostfr.net`

Remove dead domains

---

english.txt

`thisisfutbol.com`
https://github.com/easylist/easylist/commit/64ab906b61dc8e8aa71334ca85bfc08505dc486c
`footballtransfertavern.com`
https://github.com/easylist/easylist/commit/a761fa99678ea0598010231f980723630a0476ba
`footballleagueworld.co.uk`
https://github.com/easylist/easylist/commit/09fce829b662a549c9393f2955a76d74d304d0e2
`celticquicknews.co.uk`
https://github.com/easylist/easylist/commit/2c87e3bee698a9ddecaa7baf4a3b50f33e270679
`thecelticblog.com`
https://github.com/easylist/easylist/commit/c784c16fa207b43df3969bfe714275632356e6ff
`videocelts.com`
https://github.com/easylist/easylist/commit/191aa0e26e3914272be456a7c9d4fd3de7774d91

Remove cloudfront.net dubes, now in Easylist

---

english.txt

Wasn't sure where to stick this, so I put it under the exisiting 9to5google filters.
Without this filter, ads will be loaded from this site. (Using some 3rd-party->1st-party hooks) to show the ads.

Prevent ads from loading through first-party items

---

english.txt

Same script used on 9to5google/9to5 mac. this will prevent the ads from loading.
See for more info: `https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1444`

Block Apomaya Adgain scripts from loading

---

english.txt

This a popup ad script, blocking the following will prevent a full window from popping up. 
vev and vidop, vidup are mirrors of the same domains:
`https://vev.red/qnoxpkl5lm30`
`https://vidop.icu/y6w1glonjw1q`

Fix popup ads on vidop / vev / vidup

---

english.txt

This helps preventing the famous `White Screen` unskippable ad issue being experienced by a us and other adblockers.  Will be applicable with ABP 3.9.4 release.
Related fixes I also rolled out: https://github.com/brave/adblock-lists/pull/432  & https://github.com/brave/adblock-lists/pull/420

Additional Fixes for youtube.com

---

english.txt

Just to sync with other filters, https://github.com/uBlockOrigin/uAssets/pull/7756 and https://github.com/brave/adblock-lists/pull/442
Used `https://www.youtube-nocookie.com/embed/JwV1iWE8xY0`
and embeded: `https://www.racingcircuits.info/europe/norway/arctic-circle-raceway.html#.XzMw2CiA4uX`
We should also cover `youtube-nocookie.com` domain for our current youtube snippets.

Cover domain youtube-nocookie.com in youtube snippet

---

czech.txt

A new non-ad element `.Result-dw-wrapper` may appear to some users, which causes the whole organic result `.Result.Result--organic` to get blocked by this filter.

Update search.seznam.cz filter in czech.txt

---

polish.txt

`o2.pl#$#abort-on-property-read prebidConfig.hb` filter breaks `poczta.o2.pl/d/` and makes using email inbox difficult.
This filter does not break any other website.

poczta.o2.pl

---

english.txt

Was reported in the forums, https://forums.lanik.us/viewtopic.php?f=64&t=45739
`indishare.org,dailyuploads.net#$#abort-on-property-read btoa`  was causing issues with the captcha, which I could reproduce.
Updated the filter to cover these ads/popups.
Tested on `https://dailyuploads.net/ug1evlgeyr0z` and `https://www.indishare.org/myjhjfw77fr5`

Fixes https://dailyuploads.net/ filter

---

czech.txt

Hi, we've found out that this list blocks non-ad results with an image on search.seznam.cz video search.
example: https://search.seznam.cz/videa/?q=karel%20gott

Fix false-positives on search.seznam.cz

---

vietnamese.txt

mitom1.tv currently redirect to socolive.org with new website structure so this rule is outdate

D: mitom1.tv

---

vietnamese.txt

playmt.fastlycdn.xyz domain previously is being use as embed of mitom1.tv but currently mitom1.tv redirect to new domain and does not use playmt.fastlycdn.xyz as embed

D: MISC #1049

---

vietnamese.txt

Block preroll video ads on https://vebo.live/
Step to reproduce:
1. Go to website
2. Click to any link has green dot. Preroll video will display in player

A: MISC #1053

---

vietnamese.txt

xoilac19.net and xoilac19.tv randomize redirect between so both domain must be include in rule set

A: MISC #1259

---

vietnamese.txt

* `bongda365a.net` redirected to `bongda365a.club`
* `truyengihotne.com` redirected to `truyengihotday.net` and rule need to updated to `abort-current-inline-script WebAssembly instantiate`
* `viet69.love` redirect to `viet69.vc`
* `ophimmoi.net` redirected to `phimmoik.net` and rule is outdated
* `tinsoikeo.io` redirected to `tinsoikeo.vip`
* `vcomic.net` redirected to `protruyen.xyz` and rule is outdated
* `truyen86.com` redirected to `tutientruyen.xyz` and rule is outdated
* `zo3x.vip` redirected to `zo3x.lol` and rule is outdated
* `zo3x.cc` redirected to `zo3x.lol` and rule is outdated
* `zo3x.ml` and `zo3x.com` is dead domain
* `phimmoi2s.com` redirected to `phimmoi4s.com`
* `animevisub.net` redirected to `animevi.net` and rule is outdated
* `tapmoi.net`, `g18vn.com`, …

D: MISC(#1390)
